In [1]:
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

# Crear la matriz original
original = np.array([[0, 0, 0, 0, 0],
                     [0, 1, 1, 1, 0],
                     [0, 1, 1, 1, 0],
                     [0, 1, 1, 1, 0],
                     [0, 0, 0, 0, 0]], dtype=np.uint8)

# Crear la matriz de máscara para el suavizado
mask = np.ones((3, 3), dtype=np.float32) / 9

# Aplicar el suavizado utilizando la operación de convolución
smoothed = cv2.filter2D(original, -1, mask)

# Imprimir las matrices y la imagen creada
print("Matriz original:")
print(original)
print("\nMatriz de máscara:")
print(mask)
print("\nMatriz suavizada:")
print(smoothed)

# Mostrar la imagen original y suavizada
plt.subplot(1, 2, 1), plt.imshow(original, cmap='gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(1, 2, 2), plt.imshow(smoothed, cmap='gray')
plt.title('Suavizado'), plt.xticks([]), plt.yticks([])
plt.show()

Matriz original:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

Matriz de máscara:
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]

Matriz suavizada:
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


NameError: name 'plt' is not defined